### PR TITLE
Implement terrain textures from alpha maps option in Blender

### PR DESCRIPTION
**Pull request by davidrios**
Implement the option to do terrain texture blending directly in Blender when using the "Alpha Maps" terrain texture quality export option.

### CODE REVIEW

**Comment by briochie** [comment]
Using the wow.export blender addon already does this

**Comment by davidrios** [comment]
Well, I wouldn't have opened the PR if that were the case, don't you think? You can check the code, it's not that complicated.

**Comment by briochie** [comment]
> Well, I wouldn't have opened the PR if that were the case, don't you think? You can check the code, it's not that complicated.

I don't know why you would be so aggressive in a response to a reasonable question. That won't get your code reviewed any faster.

Can you explain what you mean by "terrain blending?" The included importer already creates tile materials. Is this a change for a different version of blender? The diff is too dense and I don't see what your changes actually are, other than one small line tweak at the top of the file.

**Comment by davidrios** [comment]
Sorry if I have sounded aggressive, that was not my intent.

Right now there are a few options for terrain textures when exporting a map:

- Alpha Maps: exports the texture maps the game uses to blend the terrain. It's an RGB image where each channel is supposed to be mapped to a texture based on the color value.
- None: don't export textures
- Low, medium, etc: The exporter uses the RGB maps to bake and export the baked terrain textures with the chosen resolution.

The baked texture option doesn't produce acceptable results. The terrain when imported in Blender is either too blurry when using a low resolution, or it takes a long time and generates huge textures when selecting the highest resolution.

When one selects Alpha Maps, only the texture map information is exported and set as the terrain texture, so it's not usable directly. This is how it looks:
image

What this PR does is implement the terrain texturing directly in Blender using the mapping textures exported via Alpha Maps and the layers that are also exported via JSON, so one have full fidelity for terrain texturing and the flexibility to change them if so desired.

In the code I have just extracted the previous material creation code to a dedicated `createStandardMaterial` function, it has the same code that was previously in lines 126 - 190. I also extracted the image loading to the `loadImage` function, so it can be reused. Then I check if the user opted for terrain texturing in Blender and the map had Alpha Maps exported and if so I call `createBlendedTerrain` to create the material for the map sections, otherwise I call the standard material creation.

`createBlendedTerrain` creates a material using mix shaders to blend in the layers based on the exported information, much like the game or the baker does. An example of a created shader:
image

**Comment by Kruithne** [comment]
Hi @davidrios,

Thanks for the PR, this looks great. This is a really useful feature I think people will appreciate. A couple of notes on the implementation, if you wouldn't mind resolving them:

1. In the terrain shader, instead of using Mix Shader, use Mix Color instead. It's much more efficient and we're not doing anything more than blending colours together, so the end result is the same. On a per-material level, it doesn't make a huge difference, but when you've got 4 * 255 * tiles, it rapidly adds up.
2. The Material Output is being fed a "shader" directly from a Mix Shader node, but no shader actually went into the chain. There's a Principled BSDF node floating in the shader, but it's not actually linked up. The final Mix node should go into the Principled BSDF instead of Material Output, and then the Principled BSDF should go into the Material Output.

Before
image

After
image

**Comment by davidrios** [comment]
Sure. Mix color looks like a good idea with the current implementation, though I was thinking if it could be interesting to also replicate the shading the game does, where it also uses the alpha channel for some lighting effects. In that case I think I would need to have a Principled BSDF node after each texture, right? And it would probably be mix shaders instead of mix colors, right? I don't have much experience with Blender or 3d in general TBH, so I don't know what would be best practices here.

**Comment by Kruithne** [comment]
> Sure. Mix color looks like a good idea with the current implementation, though I was thinking if it could be interesting to also replicate the shading the game does, where it also uses the alpha channel for some lighting effects. In that case I think I would need to have a Principled BSDF node after each texture, right? And it would probably be mix shaders instead of mix colors, right? I don't have much experience with Blender or 3d in general TBH, so I don't know what would be best practices here.

The only Principled BSDF you'll need is the one at the end of the chain, before the material output. Everything before that can be done by mixing the colours, since we're only dealing with colour channels. I'd say for a first prototype, keep it with the basic blending as done here, and we'll ship that.

For a v2, look at adding more advanced handling in, most of which is available here: https://wowdev.wiki/ADT/v18

I know some of the data necessary is exported by wow.export, although I can't remember what format and what setting it's behind, but if there's data missing, we'll work on getting that exported in a sensible format to accommodate what the shader needs.

**Comment by davidrios** [comment]
Cool, that makes sense. I'll change it to use mix colors now then.

**Comment by davidrios** [comment]
BTW, if you don't mind me asking, how do you enable showing the previews above the shader nodes like in your screenshots?

**Comment by Kruithne** [comment]
> BTW, if you don't mind me asking, how do you enable showing the previews above the shader nodes like in your screenshots?

It's an add-on called Node Preview by Simon Wendsche

https://blendermarket.com/products/node-preview

**Comment by davidrios** [comment]
Done changing to mix color.

**Comment by Kruithne** [comment]
> Done changing to mix color.

image

Some of the links between nodes appear to have gone missing since the change. The three mix nodes don't have any input (other than the factor) and no output links, resulting in a blank output.

**Comment by davidrios** [comment]
Dang it, worked in 4.0. Had to add compatibility code because previous versions don't properly translate socket names based on the mix node data_type.

Blender 4.0:
image

Previous versions:
image

**Comment by Kruithne** [comment]
Working fine in Blender 4.0.1, but still not resolved in Blender 3.5.0

Blender 3.5.0:
image

**Comment by davidrios** [comment]
I have now tested in Blender 3.3, 3.4, 3.6 and 4.0. Should also work on 3.5, right?

**Comment by Kruithne** [comment]
> Done. I'm thinking now that it might be best for the "Use terrain blending" to be on by default, since it won't do anything if the alpha maps weren't exported anyway.

I agree with that. If you can set that as the default and fix the merge issue with the changelog, I'll merge this PR and we'll ship it with 0.1.61.

**Pull request merged**
