### PR TITLE
(Blender) Fix error when importing with the addon in 4.0

### PR DESCRIPTION
**Pull request by Fia3D**

### CODE REVIEW

**Comment by Marlamin** [comment]
Will this keep working on older Blender versions and if not is there any way to ensure that with a version chexk or something?

**Comment by Fia3D** [comment]
> Will this keep working on older Blender versions and if not is there any way to ensure that with a version chexk or something?

Look the line, it check the version of blender, if it's 4.0.0 or more it use the new specular name.
It's not a huge change, I tried lots of other import and didn't got other direct error

**Comment by Marlamin** [comment]
Ah, must have missed that (don't look at PRs right after waking up). Awesome, thanks!

**Review by briochie — CHANGES_REQUESTED** [review]
@Fia3D  I think @Marlamin's question raises a good point: the code is a little hard to read unless you already know what it does.

Can you break this down into multiple lines, and add a comment that explains those numbers are related to Blender's version? Making this part of an if statement will also help us follow this kind of pattern should they change the name yet again in the future.

**Comment by briochie** [comment]
Something like this is what I had in mind:
```
specularName = 'Specular'

# Changes made in newer versions of blender
if (bpy.app.version >= (4, 0, 0)
  specularName = 'Specular IOR Level'

principled.inputs[specularName].default_value = 0
```

**Review by briochie — APPROVED** [review]

**Pull request merged**
